### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by softexpert** [danawoodman/go-echo-htmx-templ#1]
Hello,

First of all, thank you for this interesting example.
There are, however, some missing steps that prevent me to correctly start using the sample provided.
1. I don't know what is **gochange** - there could be some different tools out there corresponding to this exact name
2. Please specify what **npm** commands should be executed in order to bring up the required dependencies (for a system where none of them are present)
3. Under what license is this sample provided ?
4. What additional tooling is necessary to have this example up and running?

So far I deducted (some of ?) the needs for step 2 (`npm install --save-dev --save-exact prettier`) but I definitely have no idea for the other steps.

Thank you in advance for your eventual feedback !

Best regards,
SoftExpert

**Comment by danawoodman** [comment]
1. I renamed the project to [`cng`](https://github.com/danawoodman/cng) and haven't updated the repo to reflect that, but you can use any file watcher you want 😅 
2. It is in the readme, just run `make` in dev mode 👍 
3. MIT
4. Besides Golang, Node you'll need cng and templ CLI tools installed. Once you have those, just run `npm install` then `make`
